#!/bin/bash
# sxfetch by sakaki91

VERSION="2.1"

if [[ $1 == "--version" || $1 == "-v" ]]; then
    printf "sxfetch-$VERSION\n" ; exit
fi

. /etc/os-release ; OS="$NAME"
KERNEL="$(awk '{ print $1, $3 }' /proc/version)"
UPTIME_H="$(uptime -p | awk '{ printf $2 }')"
UPTIME_M="$(uptime -p | awk '{ printf $4 }')"
SHELL_I="$(basename $SHELL)"
RAM="$(awk 'NR==1 { printf "%.0f\n", $2 / 1024}' /proc/meminfo)"
FREE_RAM="$(($RAM-$(awk 'NR==3 { printf "%.0f\n", $2 / 1024}' /proc/meminfo)))"
SWAP="$(awk 'NR==15 { printf "%.0f\n", $2 / 1024}' /proc/meminfo)"
FREE_SWAP="$(($SWAP-$(awk 'NR==16 { printf "%.0f\n", $2 / 1024}' /proc/meminfo)))"
CPU="$(awk -F': ' '/model name/ { print $2 ; exit }' /proc/cpuinfo)"
CPU_CORES="($(awk -F': ' '/cpu cores/ { print $2 ; exit }' /proc/cpuinfo))"

BOLD="\033[1m"
YELLOW="\033[33m"
RESET="\033[0m"
INFO="${RESET}${BOLD}"

LINE1="    .--.     "
LINE2="   |o${YELLOW}_${RESET}o |    "
LINE3="   |${YELLOW}:_/${RESET} |    "
LINE4="  //   \ \\   "
LINE5=" (|     | )  "
LINE6="/'\\.${YELLOW}_ _${RESET}./'\\  "
LINE7="${YELLOW}\\___)=(___/${RESET}  "
         
printf "${LINE1} ${INFO}OS:${RESET} ${OS}\n"
printf "${LINE2} ${INFO}KERNEL:${RESET} ${KERNEL}\n"
printf "${LINE3} ${INFO}UPTIME:${RESET} ${UPTIME_H}:${UPTIME_M}\n"
printf "${LINE4} ${INFO}SHELL:${RESET} ${SHELL_I}\n"
printf "${LINE5} ${INFO}CPU:${RESET} ${CPU} ${CPU_CORES}\n"
printf "${LINE6} ${INFO}RAM:${RESET} ${FREE_RAM} MiB / ${RAM} MiB\n"
if [[ $SWAP != 0 ]]; then
    printf "${LINE7} ${INFO}SWAP:${RESET} ${FREE_SWAP} MiB / ${SWAP} MiB\n\n"
else
    printf "${LINE7} ${INFO}SWAP:${RESET} Disabled\n\n"
fi