#!/bin/bash
# sxfetch by sakaki91

VERSION="1"

. /etc/os-release ; OS="$NAME"
KERNEL="$(awk '{ print $1, $3 }' /proc/version)"
UPTIME_H="$(uptime -p | awk '{ printf $2 }')"
UPTIME_M="$(uptime -p | awk '{ printf $4 }')"
SHELL_I="$(basename $SHELL)"
RAM="$(awk 'NR==1 { printf "%.0f\n", $2 / 1024}' /proc/meminfo)"
FREE_RAM="$(($RAM-$(awk 'NR==3 { printf "%.0f\n", $2 / 1024}' /proc/meminfo)))"
SWAP="$(awk 'NR==15 { printf "%.0f\n", $2 / 1024}' /proc/meminfo)"
FREE_SWAP="$(($SWAP-$(awk 'NR==16 { printf "%.0f\n", $2 / 1024}' /proc/meminfo)))"
CPU="$(awk -F': ' '/model name/ { print $2 ; exit }' /proc/cpuinfo)"
CPU_CORES="($(awk -F': ' '/cpu cores/ { print $2 ; exit }' /proc/cpuinfo))"

BOLD="$(printf "\033[1m")"
YELLOW="$(printf "\033[33m")"
WHITE="$(printf "\033[37m")"
RESET="$(printf "\033[0m")"
INFO="${RESET}${BOLD}${WHITE}"

COLOR_0=${RESET}${BOLD}${WHITE}
COLOR_1=${RESET}${WHITE}
COLOR_2=${RESET}${YELLOW}

LINE1="    .--.     "
LINE2="   |o${COLOR_2}_${COLOR_1}o |    "
LINE3="   |${COLOR_2}:_/${COLOR_1} |    "
LINE4="  //   \ \\   "
LINE5=" (|     | )  "
LINE6="/'\\${COLOR_2}_   _${COLOR_1}/'\\  "
LINE7="${COLOR_2}\\___)=(___/${COLOR_1}  "
                     
printf "${LINE1} OS:        ${INFO}${OS}${RESET}\n"
printf "${LINE2} KERNEL:    ${INFO}${KERNEL}${RESET}\n"
printf "${LINE3} UPTIME:    ${INFO}${UPTIME_H}:${UPTIME_M}${RESET}\n"
printf "${LINE4} SHELL:     ${INFO}${SHELL_I}${RESET}\n"
printf "${LINE5} CPU:       ${INFO}${CPU}${CPU_CORES}${RESET}\n"
printf "${LINE6} RAM:       ${INFO}${FREE_RAM} MiB / ${RAM} MiB${RESET}\n"
printf "${LINE7} SWAP:      ${INFO}${FREE_SWAP} MiB / ${SWAP} MiB${RESET}\n\n"
